parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    modules: true
    experimentalObjectRestSpread: true
extends:
  - xo
  - xo-typescript
  - prettier
  - prettier/@typescript-eslint
  - plugin:jest/recommended
env:
  es6: true
  jest: true
plugins:
  - prettier
  - jest
rules:
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  '@typescript-eslint/restrict-template-expressions': off
  max-nested-callbacks:
    - error
    - 20
overrides:
  - files:
      - '*.spec.js'
    rules:
      '@typescript-eslint/no-var-requires': 0
globals:
  VERSION: true
