name: Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/ci

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

  check-types:
    name: Type checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/ci

      - name: TypeScript
        run: pnpm check-types

  spell:
    name: Spell checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Spell check
        uses: streetsidesoftware/cspell-action@main
        with:
          files: '**/*.{md,ts}'

  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/ci

      - name: Build
        run: pnpm build

      - name: Check exports
        run: pnpm check-exports

      - name: Test (with coverage)
        run: pnpm test:coverage

      - name: Test (with report)
        run: pnpm test:report

      - uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
